services:
  - type: static
    name: eaglercraft
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /index.html
